### ISSUE TITLE
Update Logo An Lao High School 

### ISSUE THREAD

**Issue by DatDo1309** [VNOI-Admin/uni-logo#4]
![IMG_1164](https://github.com/VNOI-Admin/uni-logo/assets/63733095/f3f1f1d1-a194-43ed-b942-017fd056ea7c)

**Comment by leduythuccs** [comment]
Hi, it would be nice if you open a PR instead of an issue. Thanks

**Comment by DatDo1309** [comment]
Tôi ko thể Pull Request được



Vào Th 7, 7 thg 10, 2023 lúc 19:42 Le Duy Thuc ***@***.***>
đã viết:
